### ISSUE TITLE
Is there any way to post tweets?

### ISSUE THREAD

**Issue by ChristianOConnor** [ardasoyturk/cloudflare-worker-twitter#2]
Can you use this to post tweets? For example could you use this to do a post request to `https://api.twitter.com/1.1/statuses/update.json?status=tweet goes here` with the proper headers and HMAC-SHA1 signing? I think the curl for that looks like this:  

```
curl --location --request POST 'https://api.twitter.com/1.1/statuses/update.json?status=tweet postman style one' \
--header 'Authorization: OAuth oauth_consumer_key="<CONSUMER KEY HERE>",oauth_token="<OAUTH TOKEN HERE>",oauth_signature_method="HMAC-SHA1",oauth_timestamp="<TIMESTAMP>",oauth_nonce="<NONCE HERE>",oauth_version="1.0",oauth_signature="SIGNATURE HERE"' \
```  

How would you run this?

**Comment by ardasoyturk** [comment]
This worker is for fetching data from the Twitter API and it uses my own API key on production. I made this tool for my other project, [Twitter Profile Viewer](https://profileviewer.site). It doesn't expose any API keys, sends the API request on the backend (with my key) and responds to you with the API response. I'd have to use your keys to post a tweet and it wouldn't make sense since you can just send a request directly to the Twitter API. In short, I won't add that feature to the worker. Thanks for your interest anyway.
